# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeid', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
